name: ffmpeg_kit_flutter_full_gpl
description: A custom version of ffmpeg_kit_flutter_full_gpl for Android embedding v2.
version: 6.0.3

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.arthenica.ffmpegkit.flutter
        pluginClass: FFmpegKitFlutterPlugin
